### ISSUE TITLE
Feature Request: add support for React.forwardRef

### ISSUE THREAD

**Issue by rsimp** [mathieutu/classed-components#4]
Some libraries require ref properties in order to use the underlying dom node. This would be a simple change and I don't mind creating a PR for it. According to react docs this should be a breaking change but I think only for code that relies on it not working currently or somehow working around it. Probably best to bump the major version just in case.

**Comment by mathieutu** [comment]
You're on fire, let's go for it!

![Let's go!](https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif)

For reference, here is the mentioned doc: https://reactjs.org/docs/forwarding-refs.html
